# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
addons:
  apt:
    packages:
    - libnetcdf-dev
    - libgdal-dev
    - libudunits2-dev
