context('Test environmental data functions.')

test_that('Testing cache creation and deletion for CRAN policy', {
  tempDir <- hoard()$cache_path_set('PAMmisc')
  saveRDS(1, file=file.path(tempDir, 'testOld.rds'))
  dir.create(tempDir)
  print(tempDir)
  betterTemp <- hoard()$cache_path_set(full_path=tools::R_user_dir("PAMmisc", which = "cache"))
  dir.create(betterTemp)
  saveRDS(1, file=file.path(betterTemp, 'testNew.rds'))
  print(betterTemp)
  expect_equal(1, 1)
  unlink(tempDir)
  unlink(betterTemp)
})
